### ISSUE TITLE
Index `SafeSetup` event of Gnosis Safe 1.3.0 to retrieve initial owner

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-subgraph#44]
**Tasks:**
- [x] Index [SafeSetup](https://github.com/gnosis/safe-contracts/blob/186a21a74b327f17fc41217a927dea7064f74604/CHANGELOG.md#add-setup-event) event in subgraph to retreive initial owner for newly deployed 1.3.0 Safes. Related PR in Safe Contracts: https://github.com/gnosis/safe-contracts/pull/279
 
**Notes:**

 This will give us compatibility with all Gnosis Safes deployed from version 1.3.0 on. Note that original Safes (aka not our forked one) will still not be supported between versions 1.0.0 - 1.3.0. This issue tries to tackle this: https://github.com/CirclesUBI/circles-subgraph/issues/59

**Comment by llunaCreixent** [comment]
**Context:**

In order to index the owner of a Safe when it's deployed, we created a fork of the `5afe/safe-contracts v 1.1.1` and introduced the emission of a `AddedOwner` event in the `setupOwners()` function of the `OwnerManager` contract.
In the version `1.3.0` of the `5afe/safe-contracts`, the aforementioned event doesn't exist (see https://github.com/safe-global/safe-contracts/blob/main/contracts/base/OwnerManager.sol#L22), but instead an event with the same purpose has been added in the etup()` funcion of the `GnosisSafe` contract (see SafeSetup event in https://github.com/safe-global/safe-contracts/blob/main/contracts/GnosisSafe.sol#L96).

Since we want the subgraph to index the data coming from both Safe versions we need to add a handler for the SafeSetup event.

**Comment by llunaCreixent** [comment]
The only drawback with this approach is that we are registering all the Safes, and not only the ones that signed up to the Hub.
We should re consider if we want to index only the Safes that are signed up to the Hub. We could do it by checking if the Safe is signed up every time we create a new Safe entry in the subgraph database.

**Comment by llunaCreixent** [comment]
Created a new issue: https://github.com/CirclesUBI/circles-subgraph/issues/85
